$('#sortone').on('click', function(event) {
    if($('#sorttwo').hasClass('btn-white')){
        $('#sorttwo').removeClass('btn-white');
    }
    if($('#sortthree').hasClass('btn-white')){
        $('#sortthree').removeClass('btn-white');
    }
    if($('#sortfour').hasClass('btn-white')){
        $('#sortfour').removeClass('btn-white');
    }
    if(!$(this).hasClass('btn-white'))
          $(this).addClass('btn-white');
  });
  $('#sorttwo').on('click', function(event) {
    if($('#sortone').hasClass('btn-white')){
        $('#sortone').removeClass('btn-white');
    }
    if($('#sortthree').hasClass('btn-white')){
        $('#sortthree').removeClass('btn-white');
    }
    if($('#sortfour').hasClass('btn-white')){
        $('#sortfour').removeClass('btn-white');
    }
    if(!$(this).hasClass('btn-white'))
          $(this).addClass('btn-white');
  });
  $('#sortthree').on('click', function(event) {
    if($('#sortone').hasClass('btn-white')){
        $('#sortone').removeClass('btn-white');
    }
    if($('#sorttwo').hasClass('btn-white')){
        $('#sorttwo').removeClass('btn-white');
    }
    if($('#sortfour').hasClass('btn-white')){
        $('#sortfour').removeClass('btn-white');
    }
    if(!$(this).hasClass('btn-white'))
          $(this).addClass('btn-white');
  });
  $('#sortfour').on('click', function(event) {
    if($('#sortone').hasClass('btn-white')){
        $('#sortone').removeClass('btn-white');
    }
    if($('#sorttwo').hasClass('btn-white')){
        $('#sorttwo').removeClass('btn-white');
    }
    if($('#sortthree').hasClass('btn-white')){
        $('#sortthree').removeClass('btn-white');
    }
    if(!$(this).hasClass('btn-white'))
          $(this).addClass('btn-white');
  });
  $('#dataone').on('click', function(event) {
    if($('#datatwo').hasClass('btn-white')){
        $('#datatwo').removeClass('btn-white');
    }
    if($('#datathree').hasClass('btn-white')){
        $('#datathree').removeClass('btn-white');
    }
    if($('#datafour').hasClass('btn-white')){
        $('#datafour').removeClass('btn-white');
    }
    if(!$(this).hasClass('btn-white'))
          $(this).addClass('btn-white');
          $('#datasets').attr('src',"https://charts.mongodb.com/charts-fibonacci-qnijn/embed/charts?id=6f24ba63-b9ac-4e31-9cdb-c513f41aedbc&maxDataAge=3600&theme=light&autoRefresh=true");
  });
  $('#datatwo').on('click', function(event) {
    if($('#dataone').hasClass('btn-white')){
        $('#dataone').removeClass('btn-white');
    }
    if($('#datathree').hasClass('btn-white')){
        $('#datathree').removeClass('btn-white');
    }
    if($('#datafour').hasClass('btn-white')){
        $('#datafour').removeClass('btn-white');
    }
    if(!$(this).hasClass('btn-white'))
          $(this).addClass('btn-white');
          $('#datasets').attr('src',"https://charts.mongodb.com/charts-fibonacci-qnijn/embed/charts?id=c3e1cde9-5518-49fd-9dac-c2f87fce4567&maxDataAge=3600&theme=light&autoRefresh=true");
  });
  $('#datathree').on('click', function(event) {
    if($('#datatwo').hasClass('btn-white')){
        $('#datatwo').removeClass('btn-white');
    }
    if($('#dataone').hasClass('btn-white')){
        $('#dataone').removeClass('btn-white');
    }
    if($('#datafour').hasClass('btn-white')){
        $('#datafour').removeClass('btn-white');
    }
    if(!$(this).hasClass('btn-white'))
          $(this).addClass('btn-white');
          $('#datasets').attr('src',"https://charts.mongodb.com/charts-fibonacci-qnijn/embed/charts?id=55bb71a2-5aa2-4a86-b63f-236f30aa4cf1&maxDataAge=3600&theme=light&autoRefresh=true");
  });
  $('#datafour').on('click', function(event) {
    if($('#datatwo').hasClass('btn-white')){
        $('#datatwo').removeClass('btn-white');
    }
    if($('#dataone').hasClass('btn-white')){
        $('#dataone').removeClass('btn-white');
    }
    if($('#datathree').hasClass('btn-white')){
        $('#datathree').removeClass('btn-white');
    }
    if(!$(this).hasClass('btn-white'))
          $(this).addClass('btn-white');
          $('#datasets').attr('src',"regression.png");
  });